version: '3'
services:
  anime:
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes: 
      - .:/workspace
    ports:
      - "5004:5004" 
    restart: always  
    command: ["python3", "api.py"]